language: java

# main task, run the verify goal
script: mvn verify

# if the build succeeds, deploy the artifact (tests are skipped)
after_success:
  - git clone -b travis https://github.com/daisy/maven-parents.git target/travis
  - ./target/travis/maven_deploy.sh

# whitelist; only deploy master branch
branches:
  only:
  - master

env:
  global:
    - secure: "Vn2O8sDLSo+fNy4HKWJP4+qqkzCuCku0M8Ti6gOSFWoo/M3bI6Xp2GfeV4RHK7+qscV0DS9YHZTT50VkANQU0KJzjyxKZKoWajc00ToSafx7RmIf3cAiNhWPdsML/ucNvVIxhmlkXS2Wup7+530o+FEFS+hNbrpU4WcIgGX8rOk="
    - secure: "V9ygqgtZKSfoARVGyRz/wiOqqpXXdOVWTvuyecwUspF/g5HQKh/OiabXrKakmrnKi/JfIa2tezOAtbyP/DZWlRju7xubrKUHnMFgGS4UbtheHuqEOUmI6xzQgSAvmn2aitCwYH2T0GXIDPOHYC6imyIVR8hJuGwLovc1PKkkETE="
